name: myapp
description: "Flutter app for running small LLM models locally on Android devices."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2         # Керування станом
  path_provider: ^2.1.4    # Доступ до локального сховища
  sqflite: ^2.3.3+1        # Локальна база даних
  http: ^1.2.2             # Для завантаження моделей
  shared_preferences: ^2.3.2 # Зберігання налаштувань
  ffi: ^2.1.2              # Інтерфейс для інтеграції з llama.cpp
  path: ^1.9.0             # Керування шляхами
  flutter_markdown: ^0.7.3+1 # Відображення markdown
  animated_text_kit: ^4.2.2 # Анімація генерації тексту

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true